import { IStation } from '@/modules/station/types.ts'

const createItem = (
  id: string,
  url: string,
  format: string,
  name: string,
  description: string,
  website: string,
  logo: string,
  cover: string,
  genres: string[],
  type: string,
): IStation => {
  return {
    id,
    url,
    format,
    name,
    description,
    website,
    logo,
    cover,
    genres,
    type,
    isFavorite: false,
  }
}

export enum StationTypes {
  Music = 'music',
  Podcast = 'podcast',
}

export enum Genres {
  ROCK = 'rock',
  POP = 'pop',
  BLUES = 'blues',
  CLASSICAL = 'classical',
  JAZZ = 'jazz',
  COUNTRY = 'country',
  FOLK = 'folk',
  ALTERNATIVE_ROCK = 'alt rock',
  FUNK = 'funk',
  SOUL = 'soul',
  RNB = 'r&b',
  DISCO = 'disco',
  HITS = 'hits',
}

const listStations = (): IStation[] => {
  return [
    createItem(
      'somafm-folk-forward',
      'https://ice4.somafm.com/folkfwd-128-mp3',
      'mp3',
      'Folk Forward',
      'Contemporary indie folk music. Sometimes softer, sometimes a little harder, but always authentic. A modern take on classic folk music, with occasional appearances by the classic masters.',
      'https://somafm.com/folkfwd',
      'https://cdn-profiles.tunein.com/s190122/images/logod.jpg',
      `${import.meta.env.VITE_CDN_ENDPOINT}/folk.jpg`,
      [Genres.FOLK, Genres.ALTERNATIVE_ROCK],
      StationTypes.Music,
    ),
    createItem(
      'jazz24',
      'https://prod-54-159-73-9.amperwave.net/ppm-jazz24mp3-ibc1',
      'mp3',
      'Jazz24',
      'Welcome to Jazz24 from Seattle and Tacoma, Washington. Our free jazz stream features some of the all-time greatest artists, like Miles Davis, Billie Holiday and Dave Brubeck; as well as today’s top talents, like Wynton Marsalis, Diana Krall and Pat Metheny.',
      'https://www.jazz24.org',
      'https://cdn-profiles.tunein.com/s34682/images/logod.jpg',
      `${import.meta.env.VITE_CDN_ENDPOINT}/jazz.jpg`,
      [Genres.JAZZ],
      StationTypes.Music,
    ),
    createItem(
      'funky-corner-radio',
      'https://ais-sa2.cdnstream1.com/2447_192.mp3',
      'mp3',
      'Funky Corner Radio',
      'We play the best in Funky, Soul, Rhythm and Blues, Disco from the 70s and 80s.',
      'https://www.funkycorner.it',
      'https://cdn-profiles.tunein.com/s231747/images/logoq.png',
      `${import.meta.env.VITE_CDN_ENDPOINT}/blue.jpg`,
      [Genres.FUNK, Genres.SOUL, Genres.RNB, Genres.BLUES, Genres.DISCO],
      StationTypes.Music,
    ),
    createItem(
      'highway-65-radio',
      'https://hydra.cdnstream.com/1924_64',
      'mp3',
      'Highway 65 Radio',
      'Highway 65 Radio is a 365/24/7 destination for all things Music City! MCR features all genres of music found in our great city!',
      'https://www.highway65radio.com',
      'https://cdn-radiotime-logos.tunein.com/s174864q.png',
      `${import.meta.env.VITE_CDN_ENDPOINT}/country.jpg`,
      [Genres.COUNTRY, Genres.ROCK, Genres.BLUES],
      StationTypes.Music,
    ),
    createItem(
      'america-greatest-70s-hits',
      'https://hydra.cdnstream.com/1823_128',
      'mp3',
      "America's Greatest 70s Hits",
      'Playing The Greatest Hits Of The 70s!!',
      'https://www.americasgreatest70s.com',
      'https://cdn-profiles.tunein.com/s294324/images/logod.jpg',
      `${import.meta.env.VITE_CDN_ENDPOINT}/america-hits.jpg`,
      [Genres.HITS],
      StationTypes.Music,
    ),
    createItem(
      '80s-90s-hitz',
      'https://pureplay.cdnstream1.com/6038_128.mp3',
      'mp3',
      "80s 90s & Today's Hits",
      "100Hitz free internet music streaming Great music without all the fuss, frills and spills of other internet radio portals. It's fun, It's free!",
      'https://100hitz.com/radiochannel/hot-ac-hitz',
      'https://cdn-profiles.tunein.com/s111391/images/logod.png',
      `${import.meta.env.VITE_CDN_ENDPOINT}/disk.jpg`,
      [Genres.HITS],
      StationTypes.Music,
    ),
    createItem(
      'k-pop',
      'https://boxradio-edge-00.streamafrica.net/kpop',
      'mp3',
      'K-Pop',
      'Playing Hits Of K-Pop',
      'https://boxradio-edge-01.streamafrica.net/kpop',
      'https://boxradio.net/wp-content/uploads/2024/06/kpopv221.png',
      `${import.meta.env.VITE_CDN_ENDPOINT}/kpop.jpg`,
      [Genres.HITS],
      StationTypes.Music,
    ),
  ]
}
export default listStations
